#!/bin/bash
[ $# -ne 1 ] && { echo "Usage: $0 version_arg"; exit 1; }

version_arg=$1

# Build resources
# We might not always bother running ./stage manually - it's really only needed when you are doing tests in browsers that don't support native modules
./stage || exit 1;

# Tell npm to bump version in package.json, commit change, get new version
version=$(npm version $version_arg) || exit 1;

# prepend license comment to dist code
message="/*! 
	openModal $version
	(c) Alex Fischer
	https://github.com/a-p-f/openModal
*/
"

rm -r dist
mkdir dist
echo "$message" | cat - staging/openModal/openModal.js > dist/openModal-${verion}.js
echo "$message" | cat - staging/openModal/modalUtils.js > dist/modalUtils-${verion}.js
echo "$message" | cat - staging/openModal/modalUtils.css > dist/modalUtils-${verion}.css
echo "$message" | cat - staging/openModal/modalUtils.min.css > dist/modalUtils-${verion}.min.css

tar -cxz dist > dist.tar.gz

# npm publish
# git push
# git push origin $version
